### PR TITLE
Add shortcuts to the readme

### PR DESCRIPTION
**Pull request by achamney**

### CODE REVIEW

**Review by TheSpaceSheep — APPROVED** [review]
Wow this is the first time someone ever makes a request on one of my repos ! Thank you for participating :)

**Comment by achamney** [comment]
Hopefully it helps! I had to look through the code to figure out the
hotkeys....

**Comment by achamney** [comment]
I don't have write access so you'll have to hit merge

**Comment by TheSpaceSheep** [comment]
Oh, normally when you launch the program, the hotkeys are supposed to be written right on the window

**Comment by achamney** [comment]
Ah, I hit the start tracking button before reading I guess haha...

**Pull request merged**
